@weapons = http://localhost:8000/tf2sc/weapons
@loadouts = http://localhost:8000/tf2sc/loadouts


### 
GET {{weapons}}?merc=Engineer&slot=primary HTTP/1.1
Content-Type: application/json

### 
GET {{weapons}} HTTP/1.1
Content-Type: application/json







# 199 - valid primary for engie

###
# @name postALoadout
POST {{loadouts}} HTTP/1.1
Content-Type: application/json

{
    "merc": "Engineer",
    "primary": 199,
    "secondary": 140,
    "melee": 30758,
    "name": "prinny engie"
}

###
@loadoutId = {{postALoadout.response.body.id}}
###

###
# @name getALlLoadouts
GET {{loadouts}} HTTP/1.1
Content-Type: application/json

###
# @name getLoadoutById
GET {{loadouts}}/{{loadoutId}} HTTP/1.1
Content-Type: application/json

###
# @name updateALoadout
PUT {{loadouts}}/{{loadoutId}} HTTP/1.1
Content-Type: application/json

{
    "merc": "Engineer",
    "primary": 199,
    "name": "updated prinny engie"
}

###
# @name deleteALoadout
DELETE {{loadouts}}/{{loadoutId}} HTTP/1.1
Content-Type: application/json
